apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-receiver
  labels:
    app: webhook-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-receiver
  template:
    metadata:
      labels:
        app: webhook-receiver
    spec:
      containers:
      - name: receiver
        image: webhook-receiver:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ADDR
          value: ":8080"
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver
spec:
  selector:
    app: webhook-receiver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
