replicaCount: 1

image:
  repository: webhook-receiver
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

env:
  addr: ":8080"

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  allowPrivilegeEscalation: false

notifications:
  slack:
    enabled: false
    webhookUrl: ""

  telegram:
    enabled: false
    botToken: ""
    chatId: ""

metrics:
  enabled: true
  path: /metrics
  port: 8080

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
