name: Trigger ArgoCD Sync

on:
  push:
    branches:
    - main # roda apenas quando um PR é mergeado na main

jobs:
  build-and-sync:
    name: Build CLI and Trigger ArgoCD Sync
    runs-on: ubuntu-latest

    env:
      GO_VERSION: '1.21'
      ARGOCD_APP: 'my-app'
      ARGOCD_SERVER: 'https://argocd.example.com'
      ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
      ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}

    steps:
    - name: 🧬 Checkout code
      uses: actions/checkout@v4

    - name: 🛠️ Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: 🔍 Lint Go code
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...

    - name: 🧪 (Optional) Run tests
      run: |
        go test -v ./...

    - name: ⚙️ Build CLI binary
      run: |
        go build -o bin/argocd-sync ./cmd

    - name: 🔑 Authenticate with ArgoCD (CLI)
      run: |
        curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd
        sudo mv argocd /usr/local/bin/

        argocd login $ARGOCD_SERVER \
          --username "$ARGOCD_USERNAME" \
          --password "$ARGOCD_PASSWORD" \
          --insecure

    - name: 🚀 Sync ArgoCD App
      run: |
        argocd app sync "$ARGOCD_APP"
